### ISSUE TITLE
Mismatching MD5's On Different Servers

### ISSUE THREAD

**Issue by arbarlow** [sstephenson/sprockets#158]
Not sure if this is a bug or whether I misunderstand ..

Im compiling assets for production and have experimented a few different ways, but can't seem to find a way to get the same file names on all servers.

How is the MD5 hash calculated may be of help?

Im running the same command on all (3) servers and locally: "bundle exec rake assets:precompile RAILS_ENV=production"

Each giving different results. This is problematic when ideally i would like to upload them to S3 and serve from there. But as each box thinks they are at different paths, it doesn't work.

In the best scenario. I would like to do it locally, as its quicker and doesn't waste server resources. Also, if i have more than one server, it saves deciding which one to run it on...

Any thoughts?

**Comment by sebbean** [comment]
@arbarlow can you explain what you meant by 'assets ordering'? 

we're having a similar issue on various docker containers

**Comment by arbarlow** [comment]
@sebbean I honestly can't remember! But I would guess something to do with the order of the import statements? That does sound odd though and multiple docker containers may have other issues, perhaps different gem versions

**Comment by sebbean** [comment]
we eneded up just removing the digest and using: https://github.com/alexspeller/non-stupid-digest-assets (rails 4 forces digests)
