### ISSUE TITLE
Stub dependencies

### ISSUE THREAD

**Issue by josh** [sstephenson/sprockets#202]
The basic scenario is that a plugin you want to include already requires `jquery`. However, you're already including jquery on the page through a separate script tag or in a separate bundle. So the dependency is already satisfied outside the context of the asset.

```
# jquery.js
var jQuery = {};

# jquery-ui.js
#= require jquery
var jQuery.UI = {};

# application.js
#= require jquery-ui
```

Using the `stub` directive (pending name), you can exclude an asset from the the bundle.

```
# application.js
#= require jquery-ui
#= stub jquery
```
## Extra conditions
- Once an asset is stubbed, its on a blacklist and can't be unstubbed or brought back by an additional `require`.
- Any asset dependencies of the stubbed asset are blacklisted as well. In the previous example, if `jquery-ui` was stubbed, then `jquery` would be removed as well. This allows for set subtraction. So you could define a `frameworks.js` bundle and simply stub that in your application bundle to ensure no framework code is pulled in twice.
- Plugins SHOULD NOT use the `stub` directive as its meant for the application domain.

This feature is planned for 2.2.

/cc @sstephenson

**Comment by NullVoxPopuli** [comment]
can this be used with a glob?
Like, if I want to co-locate test files, I'd like to recursively stub `*.test.js`

**Comment by rafaelfranca** [comment]
This repository is moved to the rails organization.
