### ISSUE TITLE
Sprockets::FileOutsidePaths

### ISSUE THREAD

**Issue by elfassy** [sstephenson/sprockets#214]
keep getting this error even after removing the gem

```
 Sprockets::FileOutsidePaths
  ...activeadmin-0.3.0/app/assets/javascripts/active_admin/vendor.js isn't in paths
```

https://github.com/gregbell/active_admin/issues/564#issuecomment-2280248

**Comment by waseem** [comment]
I have the same issue with `sprockets 2.11.0` and `rails 4.2.4`. @firedev Did you find any solution to this problem?

**Comment by firedev** [comment]
Sorry I think it resolved by itself after numerous updates.

**Comment by waseem** [comment]
@firedev Sure thank you.

If anyone bumps into this again, I was using Heroku to deploy my application. And to bypass this error, I compiled the assets locally and then pushed it to heroku and it worked.
