### ISSUE TITLE
Source Map support

### ISSUE THREAD

**Issue by igorbernstein** [sstephenson/sprockets#310]
It would be nice if sprockets pipeline was able to handle SourceMaps.
http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

Google's closure compiler already supports them & It seems like uglifyjs & coffeescript are working on generating them:
https://github.com/jashkenas/coffee-script/issues/558#issuecomment-4640890
https://github.com/mishoo/UglifyJS/issues/315

**Comment by gkatsanos** [comment]
@elia  can we safely use the 4.0 branch?

**Comment by elia** [comment]
@gkatsanos no idea, not using it on any app, you should ask @josh

**Comment by gkatsanos** [comment]
@elia What I'd like to ask if if there's some idea on when we're gonna have it :) I am still under the shock of realizing there's no proper SASS debugging possibility for one of the most hyped frameworks.

**Comment by elia** [comment]
Don't know much more than this: https://github.com/sstephenson/sprockets/issues/643

**Comment by veryeasily** [comment]
has this issue been resolved? it appears like no...

**Comment by halilim** [comment]
Looks like the latest work is happening at https://github.com/rails/sprockets/pull/206.
