### ISSUE TITLE
Cannot include assets without a file extension

### ISSUE THREAD

**Issue by DanielHeath** [sstephenson/sprockets#347]
Unpacking javascript libraries into vendor/assets results in an error "Asset logical path has no extension" when compiling assets.

This is an issue as many 3rd party javascript libraries include a 'LICENCE' file.

For the moment we can just delete those files each time we upgrade the library but ideally that wouldn't be necessary.

**Comment by loureirorg** [comment]
+1. Same problem here. I'm monkey-patching my no-extension files :/

**Comment by cseelus** [comment]
+1 

Also a problem with OSXs 'Icon\r' files used by Google Drive/Dropbox. See http://superuser.com/questions/298785/icon-file-on-os-x-desktop

**Comment by baweaver** [comment]
https://github.com/vitalets/angular-xeditable/pull/426

Still a perpetual issue, and really not a fan of having to jump through multiple 'fixes' to resolve this every time it comes up. This needs to be fixed in the base code as a default option, not a configuration flag.

**Comment by mariohmol** [comment]
+1 same here
