### ISSUE TITLE
Invalid CSS is generated when magic comment has special format

### ISSUE THREAD

**Issue by cpetschnig** [sstephenson/sprockets#368]
We have a Rails engine, which has the file `vendor/assets/stylesheets/engine_name.css`:

```
/*= require_tree .
 */
```

When precompiling the assets of the host app, it fails with the error message

```
Invalid CSS after " */": expected identifier, was ""
```

When looking at the generated Sass code, there is a closing comment without an opening comment. Our workaround is changing the file like this:

```
/*
 *= require_tree .
 */
```

Here is the list of the relevant gems in the project:
- rails (3.2.8)
- coffee-rails (3.2.2)
- coffee-script (2.2.0)
- coffee-script-source (1.3.3)
- compass (0.12.2)
- therubyracer (0.10.2)
- sprockets (2.1.3)
- sass (3.2.1)
- sass-rails (3.2.5)
- uglifier (1.3.0)
- tilt (1.3.3)

**Comment by dieggofaustino** [comment]
Thanks, works for me
