### ISSUE TITLE
Stub causes shared dependency not to be required

### ISSUE THREAD

**Issue by derekprior** [sstephenson/sprockets#467]
Consider the following manifests:

application.js:

``` javascript
//= require jquery
//= require_tree .
//= stub active_admin
```

active_admin.js:

``` javascript
//= require jquery
//= require a_bunch_of_other_stuff
```

The `stub` directive in application.js causes all of active_admin.js' dependencies to also be stubbed. I'm seeing that this causes jquery to be stubbed, even in face of the explicit require in application.js  It does not seem to matter where I add the stub directive in relation to the jquery require. 

Is this behavior intentional? It seems to me that an explicit require at the same level or higher than the stub should override the stub.

**Comment by AvaelKross** [comment]
i can't understand if it's solved somehow or not; `stub_flat`, `stub_recursive`, etc. aren't implemented yet

only solution is to remove `require_tree` and include files manually one by one (so stubbing isn't needed)
