### ISSUE TITLE
Add nocache directive to prevent erb files from being cached

### ISSUE THREAD

**Issue by rymohr** [sstephenson/sprockets#486]
This could be used to disable caching of individual `.erb` assets without having to disable it for all of them (avoiding #210).

Alternatively, this could be handled through a preprocessor instead: eg `asset.js.erb.nocache`

---

Background:

In my case I needed client-side access to the manifest in order to dynamically load the digest versions of the assets on demand.

Example: `app/assets/javascripts/manifest.js.erb`

```
window.Manifest = <%= asset_manifest %>;
```

When changes are made to the `asset_manifest` helper or new assets are added, they won't be reflected in the underlying asset until A) you manually clear the cached asset, or B) bump the assets version.  Both solutions are overkill for such a simple need.

Right now I'm working around this by having the `asset_manifest` helper inject an inline script tag to initialize the manifest instead.  But now if you view source you see a big fat ugly manifest hash. The separate `manifest.js.erb` approach feels a lot cleaner but the caching issues prevent it from being practical.

**Comment by hammady** [comment]
Hey, I had the same issue and got the solution from #563. There you will find my example.

**Comment by jeremyhaile** [comment]
I also would love a nocache directive or some solution to the problem of dynamically generated code from variables. We have a set of constants that get mirrored to the client-side and it's such a pain and source of bugs to clear the cache anytime any of those constants change.
