### ISSUE TITLE
Compilation error on gzip assets

### ISSUE THREAD

**Issue by sheerun** [sstephenson/sprockets#519]
It happens for example for stylus which calls `path_to_asset` for all paths from `each_logical_path` (https://github.com/lucasmazza/ruby-stylus/blob/master/lib/stylus/tilt/rails.rb#L40).

If one of the paths is `.gzip` file, then an error is raised (it happens because sprockets is unable to compute sha needed for url generation for such files).

Example error message:

```
angular.min.js.gzip has a invalid UTF-8 byte sequence
```

I guess the solution is to recognize if file is in binary format and don't try to read it as utf-8.

**Comment by dfabreguette-ap** [comment]
Hi,
I'm getting this error as I pulled in angularJS in an existing app through bower. Which sprockets gem version will solve this issue ?

**Comment by gustiando** [comment]
Same here. any ideas?
