### ISSUE TITLE
Disable .erb caching in development

### ISSUE THREAD

**Issue by rymohr** [sstephenson/sprockets#563]
This is a follow up to #486.

My original suggestion to add a `nocache` directive is too heavy-handed. Instead, I think simply not caching .erb assets in development is the proper way to go.  Better yet, piggyback on `config.cache_classes` or `config.action_view.cache_template_loading` to decide if these assets are cached or not.

Caching them in development makes them practically useless as mentioned by @PikachuEXE and @dekart.

In production these assets should always be cached and served separately by the asset host.  If you need these to be dynamic in production just use a standard AC view to generate the javascript dynamically as @josh mentioned.

**Comment by jeremyhaile** [comment]
I successfully used `depend_on_asset` to solve this problem!

**Comment by zampino** [comment]
great! @dekart thanks for the solution! I finally understood `depent_on_asset` vs `depend_on`

**Comment by hammady** [comment]
This solved my problem, Thanks! I had a routes_json.js.erb that is never changed, but depends on the changing routes.rb (I want routes to be available in the static js client views).
This is how I did it:

    # app/assets/javascripts/routes.js.erb
    <% depend_on Rails.root.join('config').join('routes.rb') %>
    routes_hash = <%= MyApp::Application.routes_json.html_safe %>

where `routes_json` computes a json representation of the routes.
