### ISSUE TITLE
Support something like depend_on_tree

### ISSUE THREAD

**Issue by rosenfeld** [sstephenson/sprockets#567]
I use Compass for generating an image sprite and in the SASS file there's something like this:

``` scss
@import "default/theme/*.png";
```

I'd like to be able to specify the dependency on those images (they are actually mostly symbolink links to ../common/xxx.png) to force sprockets to recompile the CSS assets if the images change, using something like this:

``` ruby
#= depend_on_tree default/theme
```

I'm not sure how that would work since the tree variant usually depend on a relative path but in this case the images are in app/assets/images while the stylesheets are on app/assets/stylesheets.

I don't really care how the dependency would be specified as long as I would be able to specify them all at once like the `@import` SASS directive works.

**Comment by rstacruz** [comment]
If `depend_on` doesn't work on directories, perhaps this should be re-opened, then?

**Comment by joshjordan** [comment]
+1 for reopening. 

> Also just wanted to note you can use #= depend_on with a directory today.

does not seem to be reconciled with

> @arnvald depend_on only works on files, not directories.

I am assuming the latter is true, and that is what this issue asks to address.
