### ISSUE TITLE
Incorrect hashing algorithm information in README

### ISSUE THREAD

**Issue by MaxGabriel** [sstephenson/sprockets#657]
The README states for the 2.11.0 release:

> Default digest changed to SHA1. To continue using MD5. `env.digest_class = Digest::MD5`

If I'm not missing anything, I don't think this is correct. The 2.11.3 code [still defaults to MD5](https://github.com/sstephenson/sprockets/blob/v2.11.3/lib/sprockets/environment.rb#L32), [matching comment in base.rb](https://github.com/sstephenson/sprockets/blob/v2.11.3/lib/sprockets/base.rb#L18).

**Comment by nTraum** [comment]
Necroing this. Has the hashing algorithm changed with 2.11.0 or 3.0? If it's the latter, the Changelog is wrong:

![image](https://cloud.githubusercontent.com/assets/866318/5662502/2eea6358-973a-11e4-85a8-f5b78c2bb3bc.png)

**Comment by josh** [comment]
Maybe there was a merge conflict. 2.x is using SHA1 by default and 3.x is using SHA256 by default.

**Comment by MaxGabriel** [comment]
@josh The 2.11.3 code (linked above) looks to be defaulting to MD5. Is that just a red herring?

**Comment by josh** [comment]
Maybe not, I guess I never switched away on 2.x. I think there was some backwards compete concern so I only did it in 3.x. https://github.com/sstephenson/sprockets/blob/2.x/lib/sprockets/environment.rb#L30-L32
