### ISSUE TITLE
[Question] Best approach to keep track and access assets dependencies for SASS/SCSS files

### ISSUE THREAD

**Issue by barraq** [sstephenson/sprockets#673]
Dear all,

In order to better integrate Sprockets with Nanoc (a static site generator) I need to keep track and access the dependencies of SASS/SCSS files in order to update Nanoc dependency graph.

I've been trying to find a way to do that without success...

Usually to access an asset you do as follow:

```
    environment.css_compressor = params[:css_compressor]
    environment.js_compressor  = params[:js_compressor]

    if asset = environment[filename]
        asset.to_s
    end
```

While `asset.to_s` gives you the content of the generated asset, is there a way to access its associated dependencies (e.g. the partials included in it, etc.) ? By dependencies I mean the paths to the dependencies.

Thanks for your help.

**Comment by barraq** [comment]
Hi @josh, In on of my projects [nanoc-sprockets3](https://github.com/barraq/nanoc-sprockets/blob/master/lib/nanoc/sprockets/filter.rb) I was using

    asset = environment[filename]
    asset.metadata[:dependency_paths] #=> Set.new([ paths ])

in order to access dependency paths from my assets.

It appears that in Sprockets 3.0.0.beta.6 this was working but then somewhere between beta7 and beta8 the property `dependency_paths` disappeared from asset.metadata.

Could you please tell me how do I access assets dependency paths in the new beta of Sprockets 3.0.0 ?

Thanks for your help,
Best,
Rémi

**Comment by josh** [comment]
Ah, sorry, my bad, try just `asset.metadata[:dependencies]`. Though, I think I'd like to add something specifically for sass deps like `asset.metadata[:sass_imports]`, let me open a new issue for that.

**Comment by barraq** [comment]
Hi @josh, I did try `asset.metadata[:dependencies]` but unlike `asset.metadata[:dependency_paths]` the set is always empty :/

**Comment by barraq** [comment]
Hi @josh, I did try the `asset.metadata[:dependencies]` but unlike `asset.metadata[:dependency_paths]` it returns file-digest, right ? not path. Is there a way to map file-digest to path ?

**Comment by josh** [comment]
@barraq you'll want to filter out any non-file-digest ones and just strip that prefix. Though, thats why I would like to add back https://github.com/sstephenson/sprockets/issues/709 with just plain old filenames.

**Comment by barraq** [comment]
@josh I need to get the dependencies for both Javascripts and stylesheets. Adding back #709 (i.e. adding back `asset.metadata[:sass_imports]`) will only address stylesheets.

Tell me if I am wrong but if I want to get all the dependencies for both Javascript and Stylesheets I will have to do it using `asset.metadata[:dependencies]. Right ?

Also another question, when looking at your documentation (from the README) regarding the `metadata`, you say that `metadata[:required] returns a set of String Asset URIs that the Bundle processor should concatenate together`. Are you talking about the sprockets `require` directives ? Cause I tried to print this value for an asset containing:


```Javascript
//= require 'bootstrap-sass/js/affix'
//= require 'bootstrap-sass/js/carousel'
//= require 'bootstrap-sass/js/dropdown'

$(function() {
   $('#main-header').affix({});
   $('.dropdown').dropdown();
   $('.carousel').carousel();
});
```

and metadata[:required] for this asset is always empty :/
