### ISSUE TITLE
Yank integrity support

### ISSUE THREAD

**Issue by josh** [sstephenson/sprockets#686]
Some nice Subresource Integrity support went into the 3.x beta. However, the URI `ni:///` format itself still seems undecided. Its unclear if the spec is going to change or Chrome's current implementation.

I think I'm going to disable the feature until its sorted out.

@mastahyeti sound okay?

**Comment by mozfreddyb** [comment]
I was a little unavailable when this came up. Here's a link to the discussion for further reference: https://github.com/w3c/webappsec/pull/125

The spec is not going to change with regard to this.
We intend to move it into Last Call this month and I'm looking forward to any kind of feedback about the spec and hash function naming in `ni` URIs in particular.

**Comment by josh** [comment]
Thanks @mozfreddyb.

I forgot to mention I reverted that commit, full support is coming back now that things are resolved in Chrome Canary. 777f1ebfcbb397479d28509bce2ac67d12d40320

We're going to ship a Subresource Integrity beta on github.com pretty soon!

**Comment by mozfreddyb** [comment]
A discussion just came up whether we want to change the syntax after all. Sorry about the inconvenience :/

Please read the [**whole** thread]( https://lists.w3.org/Archives/Public/public-webappsec/2015Jan/0177.html). The pull request about this is at https://github.com/w3c/webappsec/pull/156
