### ISSUE TITLE
Concatenating minified Javascript assets 

### ISSUE THREAD

**Issue by MrJaba** [sstephenson/sprockets#691]
More of a question than an issue really, and I may well be doing it wrong, but I can't see any obvious way of including a vendor'ed minified javascript library in a bundled asset? 

So with a Rails application.js file as an example:
```
//= require a.js
//= require b.min.js
```

These will be concatenated together fine, but I believe the b.min.js will be minified again when it has already been done which seems wasteful and slows down precompile times. 

I've just run into this including tinymce.min.js which is massive, and by putting it back into public/javascripts the precompile time dropped from 581seconds to 74seconds. However, I'd like to treat it like the rest of the assets. 

Is this at all possible? Is there an engine which allows a preprocessor to skip other processors? Or should I be doing this in some other way. 

Thanks for any help

**Comment by josh** [comment]
> I've just run into this including tinymce.min.js which is massive, and by putting it back into public/javascripts

Nah, its totally fine. Anything thats already in its "final form" is definitely good to just go in public/. Hopefully that still works for you.

Thanks!

**Comment by MrJaba** [comment]
Cool, thanks for getting back to me, will carry on as normal then! 
Keep up the awesome work.
