### ISSUE TITLE
Tilt Dependency

### ISSUE THREAD

**Issue by dg-ratiodata** [sstephenson/sprockets#692]
Would you mind to allow `tilt` > 1.3 to be installed along with sprockets?

**Comment by josh** [comment]
tilt 1.4 should be allowed, and even 1.3.1, but there was a serious bug in 1.3.0, which is why that version isn't allowed.

https://github.com/sstephenson/sprockets/blob/2.x/sprockets.gemspec#L17

**Comment by dg-ratiodata** [comment]
2.x would be great.
