### ISSUE TITLE
Flag for turning off gziping of files

### ISSUE THREAD

**Issue by Jayiitb** [sstephenson/sprockets#694]
I have setup my own compiling process with rjs and sourcemapping of js files. Now I require, to turn off gzipping by default and only do gzipping once.

**Comment by josh** [comment]
good news, its off by default in 3.x. Definitely checkout the betas.

**Comment by Jayiitb** [comment]
@josh Thanks. I am using rails 4.0.5 and by default, its gzipping all the files being precompiled. How Can I stop that?

**Comment by Jayiitb** [comment]
@josh Thanks. How Can I use higher versions of sprockets? My sprockets is locked to 2.11.0 due to other dependencies like gem "sass-rails", "~> 4.0.1", have dependency of sprockets (~> 2.8, <= 2.11.0), and  gem 'haml_coffee_assets' has dependency of sprockets (~> 2.0).
