### ISSUE TITLE
JavaScript replaced with empty function

### ISSUE THREAD

**Issue by jomo** [sstephenson/sprockets#696]
I'm trying to use [smolnar/jquery-textcomplete-rails](https://github.com/smolnar/jquery-textcomplete-rails).

Rails [appends `body=1`](https://github.com/rails/sprockets-rails/blob/3b32a2bac2edef2c7b09bd895a1d71d71d493ce6/lib/sprockets/rails/helper.rb#L60) to the URL and the result is that the whole js file is replaced with this empty function:

```JavaScript
(function() {


}).call(this);
```

When I remove `body=1` that function above is appended to [the original file](https://github.com/smolnar/jquery-textcomplete-rails/blob/8e1cfc323c626f05b95220390a88a536f696b229/vendor/assets/javascripts/jquery-textcomplete/base.js#L553):

```JavaScript
// lots of stuff
})(window.jQuery || window.Zepto);
(function() {


}).call(this);
```

I'm using sprockets 2.11.0.

**Comment by josh** [comment]
Debug will split the scripts on the page into multiple scripts. The one your looking at is probably just an empty coffee script file with some requires to jquery.

See the other script files on page. Or you can off the `config.assets.debug` feature if you don't like this in dev https://github.com/rails/sprockets-rails#initializer-options

**Comment by jomo** [comment]
Just noticed as well, thank you anyway :)
