### ISSUE TITLE
Could not find gem 'sprockets (~> 3.0) ruby' in the gems available on this machine.

### ISSUE THREAD

**Issue by rassom** [sstephenson/sprockets#702]
Hi,

I've added sprockets to my gemfile like this `gem 'sprockets', '~> 3.0'` but get the error:
Could not find gem 'sprockets (~> 3.0) ruby' in the gems available on this machine.
when running `bundle update sprockets`.

Any ideas?

Thanks :)

**Comment by josh** [comment]
Sprockets 3.0 final isn't released, try the beta version.

**Comment by rassom** [comment]
Ah - the installation instructions here https://github.com/sstephenson/sprockets are a little before their time then :) 

How can I reference sprockets in my gemfile to get the beta?

**Comment by josh** [comment]
``` ruby
gem "sprockets", "~>3.0.0.beta"
```

should work.

**Comment by rassom** [comment]
It did. Thanks :)

**Comment by rassom** [comment]
Hi Josh. I tested my (Rails 4.1.9) app with 3.0.0.beta and it works great apart from breaking jquery-ui stuff. Is this something you are aware of / a general issue? If you want, I can give you access to the app repo.

**Comment by josh** [comment]
> breaking jquery-ui stuff.

Hmm, they'll probably need to make some change to the plugin.

Working on an upgrading guide right now for both app user and plugin authors. https://github.com/sstephenson/sprockets/blob/master/UPGRADING.md

Let me know if you think anythings missing.

**Comment by rassom** [comment]
I'm not a super developer myself but it looks pretty good from what I understand :)

jquery-ui is an important part of most web sites/apps, I guess, so maybe somebody should point them to the fact that it's breaking. I don't know how to explain it to them so if you could ask them to test with Sprockets 3, it would be awesome, thanks :)

**Comment by rassom** [comment]
@josh It could actually look like it's some jquery-ui javascript that's not working properly with Sprockets 3. The CSS classes seem to be imported fine like in Sprockets 2 but the behaviour is not right. I.e. I can't use my keyboard up/down keys with jquery ui autocomplete when using Sprockets 3. That was possible with Sprockets 2.

**Comment by rassom** [comment]
@josh I've looked more into it and here is an example difference between how our page is rendered with Sprockets 2 and Sprockets 3.
Sprockets 2: https://www.evernote.com/shard/s48/sh/de630b35-1bb8-4a25-85c0-5f5ae03aa0a7/e7526bd27b655b88d4ed52103c2ea96b/deep/0/sprockets2.png
Sprockets 3: https://www.evernote.com/shard/s48/sh/12cf5deb-3066-4a03-bf85-2b8b6340d0a4/c4482dc673c21bddcf5daa428d6f7a17/deep/0/sprockets3.png
