### ISSUE TITLE
JavaScript asset not found if directory has extension (.js)

### ISSUE THREAD

**Issue by ledestin** [sstephenson/sprockets#706]
Please see this bug for more detail: https://github.com/rails/rails/issues/18859

**Comment by josh** [comment]
Can you try this on the `3.0.0.beta` gem?

Its probably going to be a *wontfix* in the 2.x releases.

**Comment by bpainter** [comment]
There's a similar issue over at https://github.com/middleman/middleman-sprockets/issues/75 where Sprockets errors out if there is a symbol (parenths or + so far) in the path.

I upgraded to MM 3.3.10 and started getting the following sprockets error similar to @ledestin :

```
== The Middleman is loading
/Users/bermonpainter/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:153:in `resolve': couldn't find file '/Users/bermonpainter/Dropbox (Personal)/Sites/blendconf.com/blendconf-site/source/assets/images/content/blend-conf-icon.png' (Sprockets::FileNotFound)
```

I tried to update sprockets 3.0.0.beta.8 based on https://github.com/rails/rails/issues/18859 but got:

```
You have requested:
  sprockets ~> 3.0.0.beta.8

The bundle currently has sprockets locked at 2.12.3.
Try running `bundle update sprockets`
```

I ran  `bundle update sprockets` and `bundle update middleman-sprockets` but no luck and ended up with the terminal spitting out:

```
Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    middleman-sprockets (~> 3.1.2) ruby depends on
      sprockets (~> 2.1) ruby

    sprockets (3.0.0.beta.8)
```

I even tried to manuall update the sprockets version in my gemfile.lock to 3.0.0.beta.8 but still no luck.

```
== The Middleman is loading
== Activating: sprockets
== Reading:  Local config
== Activating: livereload
== Activating: relative_assets
== Activating: directory_indexes
/Users/bermonpainter/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.8/lib/sprockets/ejs_processor.rb:1:in `require': cannot load such file -- ejs (LoadError)
	from /Users/bermonpainter/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.8/lib/sprockets/ejs_processor.rb:1:in `<top (required)>'
	from /Users/bermonpainter/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.8/lib/sprockets/ejs_template.rb:1:in `require'
	from /Users/bermonpainter/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.8/lib/sprockets/ejs_template.rb:1:in `<top (required)>'
```

**Comment by ledestin** [comment]
@josh Reproduced on `3.0.0.beta.8`.

**Comment by josh** [comment]
Moving repos https://github.com/rails/sprockets/issues

**Comment by tomheathershub** [comment]
I had the same error: /source/assets/images/marker-icon.png' (Sprockets::FileNotFound)
I removed the spaces and brackets from the root folder directory and this resolved the issue.

Hope that helps someone.

**Comment by ledestin** [comment]
@josh it seems that this bug wasn't moved to the new repo?
