### ISSUE TITLE
Resource generated in postprocessor is not included in the manifest file

### ISSUE THREAD

**Issue by pkuczynski** [sstephenson/sprockets#711]
I am generating a webp image in my post processor in a following way:

````
app.assets.register_mime_type 'image/png', '.png'
app.assets.register_postprocessor 'image/png', :png_webp do |context, data|
     # ... generate webp file
end
````

Unfortunately this file is not being added to manifest, so next time I deploy my app with Capistrano, its being wiped out.

How can I then add this new file to the manifest?

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#175
