### ISSUE TITLE
Create stub with regular expression

### ISSUE THREAD

**Issue by jonricaurte** [sstephenson/sprockets#712]
I have an angular front end and I want to include all my unit test files in my project assets(in each feature module). Currently I have to stub every test file that is included, but what would be more ideal is if I could pass in a regular expression and have stub remove all test files that end in _spec.coffee.

Thanks!

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#176
