### ISSUE TITLE
Disable file digest

### ISSUE THREAD

**Issue by Tensho** [sstephenson/sprockets#713]
Why sprockets doesn't have environment configuration for digest control? I've found the only one `digest_class=` method for specifying digest class, and that's all. Maybe this isn't `Sprockets::Environment` responsibility? I've also found that `sprockets-rails` [operates digest assets sign in context class and modify path respectively](https://github.com/rails/sprockets-rails/blob/c56e8fa05a2c9651ac8a68d2f7337492608bb71d/lib/sprockets/rails/context.rb#L29). Please clarify this moment.

**Comment by dcolebatch** [comment]
We'd love this too - for use in non-rails environments.

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.
