### ISSUE TITLE
mention missing path when sprockets can't find an asset

### ISSUE THREAD

**Issue by pravi** [sstephenson/sprockets#714]
see http://hackerheart.com/article/2013/02/undefined-method-directory-nilnilclass-while-compiling-rails-assets for sample code.

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#177
