### ISSUE TITLE
Multiline requiring has stopped work

### ISSUE THREAD

**Issue by shlima** [sstephenson/sprockets#716]
Sprockets 3.0, Multiline comments in CoffeeScript does not working now:

```coffeescript
###
= require jquery
###
```

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#178
