### ISSUE TITLE
How to declare a non-asset dependency?

### ISSUE THREAD

**Issue by pbhogan** [sstephenson/sprockets#717]
I'm not sure if this is even possible, but I'm trying to fix a bug in a gem I'm using (not my own) in a Rails project that breaks with sprockets 3 and thought maybe you could point me in the right direction.

In particular, this gem calls `depend_on` to declare a dependency on `routes.rb`:
https://github.com/railsware/js-routes/blob/master/lib/js_routes/engine.rb#L9

But since that file is not in the assets path it is rejected here in sprockets:
https://github.com/sstephenson/sprockets/blob/v3.0.0.beta.8/lib/sprockets/resolve.rb#L65

Is there a way to handle this with sprockets 3? It doesn't seem right to add the config directory to `config.assets.paths` surely.

I don't know if this is a more general problem, perhaps? Seems like any ERB processor could depend on some code elsewhere and would need to get reprocessed when the Rails environment is reloaded.

Apologies if this is more an issue for sprockets-rails, though it seems like it could apply in other circumstances too.

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.
