### ISSUE TITLE
v3.0.1 breaks index.html static files

### ISSUE THREAD

**Issue by xdmx** [sstephenson/sprockets#722]
I have sprockets 3.0.1 going through our assets and I have few with a path like `app/assets/angular/views/something/other/index.html`, after the precompile I get `public/assets/views/something/other.html` instead of `public/assets/views/something/other/index.html`.

This obviously breaks all my views, since in dev I use index.html and in production it doesn't find it

It works fine under 2.12.3

**Comment by tikijian** [comment]
+1 same for me.

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#182
