### ISSUE TITLE
could you make your error message be more readable

### ISSUE THREAD

**Issue by poc7667** [sstephenson/sprockets#727]
All the message the sprockets show us, for example `rake aborted!
end of file reached` . who knows what should we do on this error.

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#185
