### ISSUE TITLE
Stub being ignored when the enclosing bundle is required by another bundle.

### ISSUE THREAD

**Issue by tiegz** [sstephenson/sprockets#728]
Say you have this JS file structure:

```
views
  foo
    bar.js
application.js
application_wrapper.js
```    

And the relevant contents are:

`application.js`:
``` js
//= require_tree ../views
//= stub ../views/foo/bar
```

`application_wrapper.js`:
``` js
//= require application
```

In my case, `application` omits `views/foo/bar.js` from the rendered file, but `application_wrapper` still includes `views/foo/bar.js` even tho it was stubbed in `application`.

Is this expected behavior? I can help debug if it's not, just wanted to make sure before I start looking.

[NB I can reproduce this by using `require` instead of `require_tree` too, but it seemed an awkward example to `require` and then `stub` the same file]

#### VERSIONS

sprockets 3.0.0.beta.8
sprockets-rails 2.2.4

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by tiegz** [comment]
Closing for now, might reopen if I run across this again.
