### ISSUE TITLE
Serving multiple HTML files

### ISSUE THREAD

**Issue by vmvijo** [sstephenson/sprockets#730]
Is there a way to have the entire client side app (several static HTML files, and css and javacscript files which calls APIs of rails server) be a gem and installed through sprockets+bundle?

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#174
