### ISSUE TITLE
Sprockets 3.x not expanding stylesheet_include_tag

### ISSUE THREAD

**Issue by inspire22** [sstephenson/sprockets#731]
Rolling back to =2.12.4 fixed the issue.

I have no idea why; files are expanded properly in an otherwise empty rails project. 

I spent a few hours narrowing it down but was unable to.  Thought I'd post this if anyone has an idea what might be causing it.

Not the gemfile, not slim vs. erb, not application.rb or development.rb or running via puma.  Not slim.

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by inspire22** [comment]
Thanks!  I'll give it a try again soon since there's a newer version.  For now, it's just forced to 2.3.2, which is still working fine with the latest rails.
