### ISSUE TITLE
CommonJS and Sprockets4 ?

### ISSUE THREAD

**Issue by andyl** [sstephenson/sprockets#732]
Does Sprockets4 intend to support CommonJS modules and import/export?

Right now I'm using browserify-rails - it works but is slow and doesn't handle style/image assets.  My other alternative is a NodeJS build system, but I'd rather avoid that if possible.

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#173
