### ISSUE TITLE
Number of requests in development

### ISSUE THREAD

**Issue by markbrown4** [sstephenson/sprockets#733]
In development splitting out separate script includes is great for debugging so you know which file has an error, the problem is that we now have over 200 requests for our app, in development it's slowed to a chug, a crawl at best.  Even with caching it takes ages to make all of those requests and evaluate them onload.

How have others solved the problem of too many requests in development?

Here's a test page as an example of the time it takes to load with so many requests.
https://github.com/markbrown4/request_test

I'm running the example in Firefox and some dummy numbers are **7.02s** onload for 250 requests, **218ms** for the compiled equivalent.  Other build tools I'm familiar with like gulp I've always compiled in development but I haven't found a way to do that efficiently with Sprockets yet.

Edit: This seems like the way forward, is it the recommended config for development?
`config.assets.debug = false`

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#172
