### ISSUE TITLE
Bower and questions

### ISSUE THREAD

**Issue by blanchma** [sstephenson/sprockets#735]
I search for a different place to do this questions but the readme redirect me to here so:

1. The release notes says "Bower support" but there is nothing about this in the doc to know how to implement it.

2. I'm using this inside a Rack app and I want to compile/minify my assets in Production. Any clues of how to acomplish this?

**Comment by schneems** [comment]
The repo has moved over to github.com/rails/sprockets.

1) I have no idea what the bower support story is right now. 
2) You would need to run `rake assets:precompile` to reduce your assets to static files then serve those static files, maybe using something like nginx. I'll support problems you're having with Rails but i've never done a pure sprockets + rack app before. Find a tutorial online and try it out. If you think you found a bug open up a new issue in the new repo and give me an example app that demonstrates the problem.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#170
