### ISSUE TITLE
Sprockets not finding assets

### ISSUE THREAD

**Issue by lomefin** [sstephenson/sprockets#737]
I've been using gem 'bootstrap-sass' for a long while and its working fine in development.

But when sending my project to heroku I get the following error:

Sprockets::FileNotFound: could not find file: /tmp/build_3e3448ca910de3d9d48c939b8083d132/vendor/bundle/ruby/2.2.0/gems/bootstrap-sass-3.3.5.1/assets/javascripts/bootstrap/affix.js

Using Ruby version: ruby-2.2.2

Installing sprockets 3.3.3
Using sprockets-rails 2.3.2

I removed the loading error writing my own content instead of using bootrstrap-sprockets file 

Bootstrap-sprocket file requires
//= require ./bootstrap/affix

I switched them to 
//= require bootstrap/affix

But I'm getting more and more errors in other parts of my code.

**Comment by schneems** [comment]
If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

Thanks for your issue. I'm bugfixing sprockets 3.3.3 right now, the fastest way to get this fixed would be if you provide me with a small project that reproduces this issue.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#169
