### ISSUE TITLE
Sprockets depends on JavaScript

### ISSUE THREAD

**Issue by eiked** [sstephenson/sprockets#738]
Hi at sprockets.

- rails requires sprockets
- sprockets requires javascript.
- javascript is only available on x86
- --> rails only runs on x86/amd64

I'm trying to get my rails app up and running
on alternative plattforms (aka porting)

All works just fine -- ruby compiles like a charme,
but rails depends on sprockets,
and sprockets depends on JavaScript.

This is where the trouble starts.

I can't get my rails app up and running,
for the only reason, that there's no JS engine for sprockets to use.
(got that to work on osx/ppc easily, now trying freebsd/ppc)

I'd like to suggest that the sprockets gem
should work without reliance on JavaScript (on the server side)

As of my understanding, the sprockets gem collects the JavaScripts,
and compresses them by invoking some js code on the server side.

I believe, this is the only reason why a JS enigne is needed on the server side.
I'd believe a simple concateantion of the javascript codes would do as well.

Let's get rid of all the dependencies,
if we do have a cat.

cat.s:
ftp://minnie.tuhs.org/UnixArchive/PDP-11/Trees/V6/usr/source/s1/cat.s

~eike
(just kidding)

**Comment by eiked** [comment]
https://developer.ibm.com/opentech/2015/06/30/ppc-support-for-google-v8-goes-mainstream/

**Comment by rafaelfranca** [comment]
So, if I get it right you want to sprockets to stop to require a JS engine because there is no engine that works in PPC, and also V8 support PPC now, so why could not use use V8 in PPC as engine to sprockets?

**Comment by rafaelfranca** [comment]
BTW, sprockets home is now https://github.com/rails/sprockets

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#168
