### ISSUE TITLE
Can Sprockets::Context new a  new instance of Context by `manifest` or IO cache?

### ISSUE THREAD

**Issue by icai** [sstephenson/sprockets#739]
Can provide the argument `sprockets` as a file cache?

```ruby
  manifest = Sprockets::Manifest.new(environment, manifest_path)
  manifest.compile assets_compile
```
after  I instantiate the function , I close the program. then I want to reuse these compile assets,but I lose the instance of spockets `Sprockets::Context.new(sprockets, '', Pathname.new(''))`.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#167
