### ISSUE TITLE
PHPStorm Filewatcher: Only one file can be compiled to stdout at a time

### ISSUE THREAD

**Issue by duxthefux** [sstephenson/sprockets#742]
Hi,

I'm invoking sprockets from PHPStorm Filewatchers, like this:
<img width="644" alt="bildschirmfoto 2015-11-21 um 13 55 14" src="https://cloud.githubusercontent.com/assets/6758162/11318544/825fdaba-9057-11e5-811a-513d4c75ec61.png">

everytime the watcher triggers the command I get following error:
Only one file can be compiled to stdout at a time

If I run the same script from terminal, it works like a charm.

Can you help me please?

Thanks

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#164
