### ISSUE TITLE
Explicitly link to the real repo

### ISSUE THREAD

**Issue by swrobel** [sstephenson/sprockets#746]
A google search for sprockets will lead you here. The https://github.com/rails/sprockets repo seems to be the place everyone should be looking, so it should be made explicit that this is not the place to look for the source/file issues. This can be done easily with the description/website fields at the top of the github page, for example: https://github.com/swrobel/discourse-heroku

**Comment by swrobel** [comment]
README links to rails/rails, not rails/sprockets. Thanks for the quick response though!

**Comment by rafaelfranca** [comment]
oops! Fixed. Thank you for the report.
