### ISSUE TITLE
Conditional require

### ISSUE THREAD

**Issue by coder2000** [sstephenson/sprockets#90]
I am working on a rails plugin and it has support for different javascript frameworks. With the new asset pipeline however, I can't select the correct file to use. I would like to be able to determine the framework available and load appropriate javascript.

**Comment by meowsus** [comment]
@coli @tam-vo Did you ever find a solution to this? No matter where I place my ERB conditional it's always added at the end of my file.

**Comment by pjar** [comment]
Having the same issue as @alex88 - everything after an erb tags is ignored and just plain text in the compiled .js file. Any solutions for that?
